### ISSUE TITLE
 when try  find items application internal error 

### ISSUE THREAD

**Issue by sararabie** [hkonnet/laravel-ebay#1]
i use your plugin and when try use first method for list items it appear keyword not defined for request and when use 
use \DTS\eBaySDK\Finding\Types;
$request = new types\FindItemsByKeywordsRequest(); 

it work but display another error 
Error: Internal application error.  and i cant solve it please help me i need to add item to ebay and i cant each step display error please can you help me ??

**Comment by hkonnet** [comment]
Hi Sara,

The error 

> Error: Internal application error.

Usually occurs when you use invalid credentials or use sandbox credentials instead of Development credentials.

Use Development credentials in .env file.


```
EBAY_MODE=production

EBAY_PROD_DEV_ID=_______________
EBAY_PROD_APP_ID=_________________
EBAY_PROD_CERT_ID=________________
```

```
$config = Ebay::getConfig();
 
/**
 * Create the service object.
  */
 $service = new Services\FindingService($config);
 
 /**
  * Create the request object.
  */
    $request = new Types\FindItemsByKeywordsRequest();
 
 
  /**
   * Assign the keywords.
   */
    $request->keywords = 'PC';
 
 /**
  * Send the request.
 */
 $response = $service->findItemsByKeywords($request);
 
 /**
 * Output the result of the search.
 */
    if (isset($response->errorMessage)) {
        dd($response->errorMessage);
        foreach ($response->errorMessage->error as $error) {
            printf(
                "%s: %s\n\n",
                $error->severity=== Enums\ErrorSeverity::C_ERROR ? 'Error' : 'Warning',
                $error->message
            );
        }
    }
    if ($response->ack !== 'Failure') {
        foreach ($response->searchResult->item as $item) {
            printf(
                "(%s) %s: %s %.2f\n",
                $item->itemId,
                $item->title,
                $item->sellingStatus->currentPrice->currencyId,
                $item->sellingStatus->currentPrice->value
            );
        }
    }

```
Let me know if you still has the issue..

**Comment by sararabie** [comment]
hello hkonnet 
thank you for your reply but when i make  the above steps another error appear 

Server error: `POST https://svcs.ebay.com/services/search/FindingService/v1` resulted in a `500 Internal Server Error` response:
<?xml version='1.0' encoding='UTF-8'?><errorMessage xmlns="http://www.ebay.com/marketplace/search/v1/services"><error><e (truncated...)

**Comment by hkonnet** [comment]
Sara,

Did you change the credentials from sandbox to development when you create ebay developer account then app, you got 2 set of keys 1 for development one for sandbox.. you have to use **_development keys_** . Try to use them..
