### ISSUE TITLE
Trading API -> Error: No Password and no token. No XML or was found in XML Request.

### ISSUE THREAD

**Issue by price2b** [hkonnet/laravel-ebay#10]
First of all thank you for this fantastic library. Im writing because despite I tried in different ways  I cannot make ->createTrading() implementation work. With Shopping and Finding everything works ok but using createTrading I started with validation problems and "Error: No Password and no token. No XML or was found in XML Request." appeared.

My code displays the following information:

```
namespace App\Http\Controllers;
use Hkonnet\LaravelEbay\EbayServices;
use Hkonnet\LaravelEbay\Facade\Ebay;
use \DTS\eBaySDK\Constants;
use \DTS\eBaySDK\Trading\Services;
use \DTS\eBaySDK\Trading\Types;
use \DTS\eBaySDK\Trading\Enums;

class EbayTradingController extends Controller
{

        //* Create the service object.
        $ebay_service = new EbayServices();
        $service = $ebay_service->createTrading();

        //* Send the request.
        $request = new Types\GeteBayOfficialTimeRequestType();

        //* An user token is required when using the Trading service.
        $request->RequesterCredentials = new Types\CustomSecurityHeaderType();
        $authToken = Ebay::getAuthToken();
        $request->RequesterCredentials->eBayAuthToken = $authToken;

        //* Output the result of calling the service operation.
        $response = $service->geteBayOfficialTime($request);

        if (isset($response->Errors)) {
            foreach ($response->Errors as $error) {
                printf(
                    "%s: %s\n%s\n\n",
                    $error->SeverityCode === Enums\SeverityCodeType::C_ERROR ? 'Error' : 'Warning',
                    $error->ShortMessage,
                    $error->LongMessage
                );
            }
        }
        if ($response->Ack !== 'Failure') {
            printf("The official eBay time is: %s\n", $response->Timestamp->format('H:i (\G\M\T) \o\n l jS F Y'));
        }
```
The ebay.php config file seems to be ok taking into consideration it works with finding and shopping api.

Additionally I proceed to debug each statement and Appid, DevId,Cert and authToken were passed ok and complete. Only when the code reached         $response = $service->geteBayOfficialTime($request);

the response is failure

            "ShortMessage" => "Auth token is invalid."
            "LongMessage" => "Validation of the authentication token in API request failed."
            "ErrorCode" => "931"
            "SeverityCode" => "Error"
            "ErrorClassification" => "RequestError"

finally one more question:
do we have to generate tokens using: Auth'n'Auth or we have to create it using OAuth (new security)

your guideline will be appreciated. Thank you brgds!

**Comment by hkonnet** [comment]
@price2b Great to see you like the package .. Sorry about late reply.
As the ticket is closed so i am assuming you have figure out the issue. 
Regarding your second question Auth n Auth token is used.

Good Luck

**Comment by price2b** [comment]
Thank you @hkonnet ! yes Auth n Auth token + trading api worked ok. 

For OAuth user tokens I checked http://devbay.net/sdk/guides/guide/restful-services.html restful services, but its not clear for me how to include:
1- the RuName
2- the generated token for user
3- the refreshtoken code to be used

a- if we include the runame in ebay.php config it will be recognized by your library?
`    'ruName'      => 'foo'`

b- If we change the following code:
```
        //* An user token is required when using the Trading service.
        $request->RequesterCredentials = new Types\CustomSecurityHeaderType();
        $authToken = Ebay::getAuthToken();
        $request->RequesterCredentials->eBayAuthToken = $authToken;
```

and replace it by:

```
/**
 * Create the request object.
 */
$request = new Types\GetUserTokenRestRequest();
$request->code = '<AUTHORIZATION CODE>';
/**
 * Send the request.
 */
if ($response = $service->getUserToken($request) is null 
request a $response = $service->refreshUserToken($request); ?
```

c- do we need to include the $url =  $service->redirectUrlForUser([state+scope)  directly in our logic and it will be recognized?

Thank you so much!
