### ISSUE TITLE
Auth issue

### ISSUE THREAD

**Issue by rade98** [hkonnet/laravel-ebay#12]
Hi.
I'm receiving error like.
Credentials must be an instance of DTS\eBaySDK\Credentials\CredentialsInterface, an associative array that contains "appId", "certId", "devId", or a credentials provider function.

I checked every credientials for sandbox, I have authToken for user but still error. Why? I even tried to edit $authToken = Ebay::getAuthToken(); and just set token with $authToken = 'what is my token'...

**Comment by price2b** [comment]
Create a controller and check if this code returns a response

```
use DTS\eBaySDK\Trading\Enums\SeverityCodeType;
use Hkonnet\LaravelEbay\Facade\Ebay;
use Illuminate\Http\Request;
use \DTS\eBaySDK\Trading\Enums;
use \DTS\eBaySDK\Trading\Types;
use Hkonnet\LaravelEbay\EbayServices;   

 public function ebayTime(Request $request){

        //* Create the service object.
        $ebay_service = new EbayServices();
        $service = $ebay_service->createTrading();

        //* Send the request.
        $request = new Types\GeteBayOfficialTimeRequestType();

        //* An user token is required when using the Trading service.
        $request->RequesterCredentials = new Types\CustomSecurityHeaderType();
        $authToken = Ebay::getAuthToken();
        $request->RequesterCredentials->eBayAuthToken = $authToken;

        //* Output the result of calling the service operation.
        $response = $service->geteBayOfficialTime($request);
        //dd($response);
        if (isset($response->Errors)) {
            foreach ($response->Errors as $error) {
                printf(
                    "%s: %s\n%s\n\n",
                    $error->SeverityCode === Enums\SeverityCodeType::C_ERROR ? 'Error' : 'Warning',
                    $error->ShortMessage,
                    $error->LongMessage
                );
            }
        }
        if ($response->Ack !== 'Failure') {
            printf("The official eBay time is: %s\n", $response->Timestamp->format('H:i (\G\M\T) \o\n l jS F Y'));
        }
    }
```

if NO, you have to check the ebay login information you are using at config/ebay.php . This is the simplest call for trading, it uses your apptoken.

**Comment by rade98** [comment]
It's the same, I don't know what is the problem. I checked ebay.php again and there is no mistake.

**Comment by price2b** [comment]
honestly with that code and the proper credentials it must work. check the following things:
- you are using the correct sandbox/production credentials.
- make a call at ebay with the api explorer https://developer.ebay.com/DevZone/build-test/test-tool/default.aspx?index=0&env=production&api=trading&call=AddDispute&variation=xml . If your credentials are working ok you will succeed, otherwise you will see if thats the problem.

**Comment by rade98** [comment]
Yes, I'm trying now, but as I saw on the forum you already reported an issue about sandbox on the forum :)

**Comment by price2b** [comment]
Yes.
