### ISSUE TITLE
XmlParser After Request failed

### ISSUE THREAD

**Issue by SDJeff** [hkonnet/laravel-ebay#15]
ErrorException  : "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

`vendor/dts/ebay-sdk-php/src/Parser/XmlParser.php:215
    211|                 case 'string':
    212|                 case 'double':
    213|                 case 'boolean':
    214|                 case 'DateTime':
  > 215|                     continue;
    216|                 default:
    217|                     return $meta->phpType !== '' ? new $phpType() : null;
    218|             }
    219|         }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError(""continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?",`

Try to getting the EbayTime i got this error. Any ideas?

**Comment by SDJeff** [comment]
I think in L215 and L216 of vendor/dts/ebay-sdk-php/src/Parser/XmlParser.php it has to be "break;" instead of "continue;"

Then the examples are running

**Comment by hkonnet** [comment]
@SDJeff ,

Basically this issue is related to php version since you are using latest php version thats why you are receiving this..

This issue is resolved 
https://github.com/davidtsadler/ebay-sdk-php/issues/241

Try to upgrade the package .. It will solve the issue..

thanks

**Comment by McMazalf** [comment]
Risolto un cazzo

**Comment by Sealtyel** [comment]
I don't think this is resolved guys, I just checked and the latest stable version (master) of davidtsadler/ebay-sdk-php doesn't have that change https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Parser/XmlParser.php
see line 215 and 261 is there a way for you to just use your own version of that library changing that?
