### ISSUE TITLE
 "continue" targeting switch is equivalent to "break". did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by abdelrahmankhedr** [hkonnet/laravel-ebay#17]
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

  at vendor/dts/ebay-sdk-php/src/Parser/XmlParser.php:215

**Comment by hkonnet** [comment]
@abdelrahmankhedr , 
This issue was reported before please take a look at [Here](https://github.com/hkonnet/laravel-ebay/issues/15) .
