### ISSUE TITLE
How to change apiVersion in service

### ISSUE THREAD

**Issue by buisine** [hkonnet/laravel-ebay#18]
Hi,

all a sudden GetOrders request have stopped to return the finalvaluefee property.
Of course IncludeFinalValueFee was set to true

My code has stopped working because this $transaction->FinalValueFee->value is not returned anymore.

[apiVersion] => 1057 ( got it from createTrading method )

is this because of old api API version how to override this value please ?

**Comment by hkonnet** [comment]
@buisine apologies for late reply. 
Did you try this
```php
$ebay_service = new EbayServices();
$service = $ebay_service->createTrading(['apiVersion'=>'your API version']);
```
