### ISSUE TITLE
sandbox problems

### ISSUE THREAD

**Issue by FooleanBool** [hkonnet/laravel-ebay#2]
Thanks for this package :)
There is a line missing from the second example 'finding' (method one):
```
//should have this line before:
$request = new \DTS\eBaySDK\Finding\Types\FindItemsByKeywordsRequest; //depending on use statement above.
$request->keywords = 'Harry Potter';
```

I spent a few hours yesterday trying to get a simple product search working from your readme example with the sandbox credentials I made, but no matter what I did, it would always return an 'unauthorised' response.
This morning, I generated production keys instead of sandbox ones and the response was the expected one on the first call. I don't know if this is a sandbox problem or what, but I thought the info may help others.

**Comment by hkonnet** [comment]
@zigstum Thank you for liking and notifying the issue in package. Documentation is updated..

And you are right finding API works on production only i it has been reported on Ebay but they didn't provide any fix yet.
