### ISSUE TITLE
Can you please update "dts/ebay-sdk-php" dependencies to release 15.00

### ISSUE THREAD

**Issue by craftyshaun** [hkonnet/laravel-ebay#5]
There has just been a new release of the "dts/ebay-sdk-php" package.
Could you please update dependencies so we can access the latest changes in the "dts/ebay-sdk-php".

ps. Thanks for a nice package :+1:

**Comment by hkonnet** [comment]
Shaun D,
Thank  you for appreciation. Modification Done and released as 1.2 version.

**Comment by craftyshaun** [comment]
Thanks for the update :+1:
