### ISSUE TITLE
Class 'DTS\ebaySDK\Shopping\Types\GeteBayTimeRequestType' not found

### ISSUE THREAD

**Issue by hoesslin** [hkonnet/laravel-ebay#6]
Hi,

your example getting ebay time works well when using as a artisan command - after a "composer dump-autoload".

But if you try to use the example in a controller, then you will get a "Class 'DTS\ebaySDK\Shopping\Types\GeteBayTimeRequestType' not found" exception...

`namespace App\Http\Controllers;
	
	use function dump;
	use Hkonnet\LaravelEbay\Ebay;
	use DTS\ebaySDK\Shopping\Types\GeteBayTimeRequestType;
	use DTS\eBaySDK\Shopping\Services\ShoppingService;
	
	
	class EapiController extends Controller
	{
	
		private $config;
		private $request;
		
		function __construct()
		{
			$ebay = new Ebay();
			$this->config = $ebay->getConfig();
			// $this->request = new GeteBayTimeRequestType();
		}
		
		public function index()
		{
			dump($this->config);
					
			// Create the service object.
			$service = new ShoppingService($this->config);
			
			// Create the request object.
			$this->request = new GeteBayTimeRequestType();
			
			// Send the request to the service operation.
			$response = $service->geteBayTime($this->request);
			
			// Output the result of calling the service operation.
			printf("The official eBay time is: %s\n", $response->Timestamp->format('H:i (\G\M\T) \o\n l jS Y'));
			
			
		}
	}`

**Comment by hkonnet** [comment]
@hoesslin Sorry for the late reply. The issue is at your use statement.

You wrote 
`use DTS\ebaySDK\Shopping\Types\GeteBayTimeRequestType;`

It should be  

> eBaySDK -> B is capital not small.

`use DTS\eBaySDK\Shopping\Types\GeteBayTimeRequestType;`
